### ISSUE TITLE
What's root password for sudo?

### ISSUE THREAD

**Issue by mizzunet** [yuvipanda/jupyter-desktop-server#30]
I just have taken fork of this repo and built it in mybinder.org. But what is root password for sudo su?

Thanks

**Comment by yuvipanda** [comment]
Hello! thanks for opening this. The image provided here does not support root access in any form, so `sudo` will not work. mybinder.org also forbids root access, so won't work there either.

If you want to add more packages, you'd need to build your own dockerfile with the packages you want added to it. Dockerfile instructions can run as root, so that's the place to do these.

Hope that's helpful!

**Comment by mizzunet** [comment]
Thank you for your reply. Well, I managed to get sudo working by RUN passwd -d root&&RUN passwd -d jovyan
But it seems, though it have a total of 51GB RAM, out of it only <2GB free RAM, rest are at "buffer/cache" and "available" sections.
By any chance, this free be increased by taking from "buffer/cache" or "available"
Sorry if it' dumb question :P

**Comment by yuvipanda** [comment]
Ah, glad it worked out! I'm not sure how to change the RAM though :'(

**Comment by mizzunet** [comment]
Oh, okie. Thanks
